[package]
name = "tex"
version = "0.1.0"
authors = ["CrLF0710"]
edition = "2018"

[dependencies]
static_assertions = "1.1.0"
typenum = {git = "https://github.com/crlf0710/typenum"}
globals_struct = {git = "https://github.com/crlf0710/globals_struct"}

[features]
initex = []
unicode_support = []
default = ['initex', 'unicode_support']
